def call(String dockerRegistry, String dockerImageTag) {
- name: Deploy Pods to EKS cluster
  hosts: localhost
  vars:
    ansible_python_interpreter: "/home/ubuntu/myenv/bin/python"
  gather_facts: no
  tasks:
    - name: Create a Deployment in Kubernetes
      community.kubernetes.k8s:
        kubeconfig: ~/.kube/config
        namespace: dev
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: books
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: books
            template:
              metadata:
                labels:
                  app: books
              spec:
                containers:
                - name: books
                  image: "061039788053.dkr.ecr.us-east-2.amazonaws.com/tom":"{{ container_image_tag }}"
                  ports:
                    - containerPort: 8080
          apiVersion: v1
          kind: Service
          metadata:
            name: books-svc
            namespace: dev
          spec:
            ports:
            - port: 8080
              targetPort: 8080
